name: X-PrisonLite
version: ${project.version}
main: dev.drawethree.xprison.XPrisonLite
depend: [ Vault, WorldGuard, WorldEdit, helper ]
softdepend:
  - Multiverse-Core
authors: [ Drawethree ]
api-version: 1.13
load: POSTWORLD
website: www.drawethree.dev
