name: UltraPrisonCore
version: ${project.version}
main: me.drawethree.ultraprisoncore.UltraPrisonCore
depend: [Vault, WorldGuard, WorldEdit]
softdepend:
  - PlaceholderAPI
  - JetsPrisonMines
  - MVdWPlaceholderAPI
  - Multiverse-Core
authors: [Drawethree]
api-version: 1.13
load: POSTWORLD
